/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyek_akhir;

import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author dHooF15
 */
public class FormAmbacinema extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAmbacinema.class.getName());
    private final Ambacinema logic = new Ambacinema();
    private JToggleButton[] arrayKursi;
    private final String[] masterJam = {"10:00", "13:00", "16:00", "19:00", "22:00"};

    /**
     * Creates new form FormAmbacinema
     */
    public FormAmbacinema() {
        initComponents();
        setupCustomComponents();
    }

    private void setupCustomComponents() {
        // Masukkan semua JToggleButton kursi ke dalam array agar mudah dikelola
        arrayKursi = new JToggleButton[]{A1, A2, A3, B1, B2, B3, C1, C2, C3};

        // Filter jam tayang saat aplikasi dibuka
        updateComboJam();
    }

    private void updateComboJam() {
        cbJamTayang.removeAllItems();
        List<String> valid = logic.getJamTayangValid(masterJam);
        for (String j : valid) {
            cbJamTayang.addItem(j);
        }

        if (cbJamTayang.getItemCount() == 0) {
            cbJamTayang.addItem("Habis");
            bLnjtKePilKursi.setEnabled(false);
        }
    }

    // Fungsi untuk mendapatkan teks film yang dipilih
    private String getSelectedFilm() {
        if (ambacong.isSelected()) {
            return "Ambacong";
        }
        if (ambatar.isSelected()) {
            return "Ambatar";
        }
        if (argoNgawi.isSelected()) {
            return "Argo Ngawi Gejes Gejes";
        }
        return "";
    }

    private void refreshKursi() {
        String film = getSelectedFilm();
        String jam = cbJamTayang.getSelectedItem().toString();

        for (JToggleButton k : arrayKursi) {
            k.setSelected(false);
            if (logic.isKursiTerpesan(film, jam, k.getText())) {
                k.setEnabled(false);
            } else {
                k.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFilm = new javax.swing.ButtonGroup();
        panelInduk = new javax.swing.JPanel();
        jPanelPilFilmDanJam = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ambacong = new javax.swing.JRadioButton();
        ambatar = new javax.swing.JRadioButton();
        argoNgawi = new javax.swing.JRadioButton();
        cbJamTayang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bLnjtKePilKursi = new javax.swing.JButton();
        jPanelPilKursi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        A1 = new javax.swing.JToggleButton();
        A2 = new javax.swing.JToggleButton();
        A3 = new javax.swing.JToggleButton();
        B1 = new javax.swing.JToggleButton();
        B2 = new javax.swing.JToggleButton();
        B3 = new javax.swing.JToggleButton();
        C1 = new javax.swing.JToggleButton();
        C2 = new javax.swing.JToggleButton();
        C3 = new javax.swing.JToggleButton();
        bKbliKePilFilm = new javax.swing.JButton();
        bLnjtKeKonfirmasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInduk.setLayout(new java.awt.CardLayout());

        jPanelPilFilmDanJam.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPilFilmDanJam.setMaximumSize(new java.awt.Dimension(405, 295));
        jPanelPilFilmDanJam.setMinimumSize(new java.awt.Dimension(405, 295));
        jPanelPilFilmDanJam.setPreferredSize(new java.awt.Dimension(405, 295));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Ambacinema");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilih Film & Jam Tayang\n"));

        bgFilm.add(ambacong);
        ambacong.setText("Ambacong");

        bgFilm.add(ambatar);
        ambatar.setText("Ambatar");

        bgFilm.add(argoNgawi);
        argoNgawi.setText("Argo Ngawi Gejes Gejes");

        jLabel2.setText("Rp. 55.000");

        jLabel3.setText("Rp. 55.000");

        jLabel4.setText("Rp. 55.000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbJamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ambacong)
                            .addComponent(ambatar)
                            .addComponent(argoNgawi))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ambacong)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ambatar)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(argoNgawi)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cbJamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bLnjtKePilKursi.setText("Lanjut");
        bLnjtKePilKursi.addActionListener(this::bLnjtKePilKursiActionPerformed);

        javax.swing.GroupLayout jPanelPilFilmDanJamLayout = new javax.swing.GroupLayout(jPanelPilFilmDanJam);
        jPanelPilFilmDanJam.setLayout(jPanelPilFilmDanJamLayout);
        jPanelPilFilmDanJamLayout.setHorizontalGroup(
            jPanelPilFilmDanJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilFilmDanJamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPilFilmDanJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPilFilmDanJamLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPilFilmDanJamLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelPilFilmDanJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPilFilmDanJamLayout.createSequentialGroup()
                                .addComponent(bLnjtKePilKursi)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPilFilmDanJamLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(149, 149, 149))))))
        );
        jPanelPilFilmDanJamLayout.setVerticalGroup(
            jPanelPilFilmDanJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilFilmDanJamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(bLnjtKePilKursi)
                .addContainerGap())
        );

        panelInduk.add(jPanelPilFilmDanJam, "pilFilmDanJam");

        jPanelPilKursi.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPilKursi.setMaximumSize(new java.awt.Dimension(405, 295));
        jPanelPilKursi.setMinimumSize(new java.awt.Dimension(405, 295));
        jPanelPilKursi.setPreferredSize(new java.awt.Dimension(405, 295));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Ambacinema");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilih Kursi\n"));
        jPanel4.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        A1.setText("A1");
        jPanel4.add(A1);

        A2.setText("A2");
        jPanel4.add(A2);

        A3.setText("A3");
        jPanel4.add(A3);

        B1.setText("B1");
        jPanel4.add(B1);

        B2.setText("B2");
        jPanel4.add(B2);

        B3.setText("B3");
        jPanel4.add(B3);

        C1.setText("C1");
        jPanel4.add(C1);

        C2.setText("C2");
        jPanel4.add(C2);

        C3.setText("C3");
        jPanel4.add(C3);

        bKbliKePilFilm.setText("Kembali");
        bKbliKePilFilm.addActionListener(this::bKbliKePilFilmActionPerformed);

        bLnjtKeKonfirmasi.setText("Lanjut");
        bLnjtKeKonfirmasi.addActionListener(this::bLnjtKeKonfirmasiActionPerformed);

        javax.swing.GroupLayout jPanelPilKursiLayout = new javax.swing.GroupLayout(jPanelPilKursi);
        jPanelPilKursi.setLayout(jPanelPilKursiLayout);
        jPanelPilKursiLayout.setHorizontalGroup(
            jPanelPilKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilKursiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPilKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPilKursiLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPilKursiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelPilKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPilKursiLayout.createSequentialGroup()
                                .addComponent(bKbliKePilFilm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bLnjtKeKonfirmasi)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPilKursiLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(149, 149, 149))))))
        );
        jPanelPilKursiLayout.setVerticalGroup(
            jPanelPilKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPilKursiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanelPilKursiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLnjtKeKonfirmasi)
                    .addComponent(bKbliKePilFilm))
                .addContainerGap())
        );

        panelInduk.add(jPanelPilKursi, "pilKursi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLnjtKePilKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLnjtKePilKursiActionPerformed
        // TODO add your handling code here:
        if (getSelectedFilm().equals("")) {
            JOptionPane.showMessageDialog(this, "Pilih Film Terlebih Dahulu!");
            return;
        }
        refreshKursi();
        // Pindah Card ke Panel Kursi
        CardLayout cl = (CardLayout) panelInduk.getLayout();

        // Tampilkan halaman kursi berdasarkan "Card Name" yang sudah diatur tadi
        cl.show(panelInduk, "pilKursi");
    }//GEN-LAST:event_bLnjtKePilKursiActionPerformed

    private void bLnjtKeKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLnjtKeKonfirmasiActionPerformed
        // TODO add your handling code here:
        String film = getSelectedFilm();
        String jam = cbJamTayang.getSelectedItem().toString();
        List<String> dipilih = new ArrayList<>();

        for (JToggleButton k : arrayKursi) {
            if (k.isSelected() && k.isEnabled()) {
                dipilih.add(k.getText());
            }
        }

        if (dipilih.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih minimal 1 kursi!");
            return;
        }

        String kursiStr = String.join(", ", dipilih);

        // Fitur 5: Konfirmasi
        int tanya = JOptionPane.showConfirmDialog(this,
                "Konfirmasi Pesanan:\nFilm: " + film + "\nJam: " + jam + "\nKursi: " + kursiStr,
                "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (tanya == JOptionPane.YES_OPTION) {
            logic.pesanKursi(film, jam, dipilih);

            // Fitur 6: Struk
            String waktuPesan = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
            JOptionPane.showMessageDialog(this,
                    "======= STRUK =======\n"
                    + "Film: " + film + "\n"
                    + "Jam Tayang: " + jam + "\n"
                    + "Kursi: " + kursiStr + "\n"
                    + "Waktu Pesan: " + waktuPesan + "\n"
                    + "=====================");

            refreshKursi();
            bKbliKePilFilmActionPerformed(null); // Kembali ke menu utama
        }
    }//GEN-LAST:event_bLnjtKeKonfirmasiActionPerformed

    private void bKbliKePilFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKbliKePilFilmActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) panelInduk.getLayout();
        cl.show(panelInduk, "pilFilmDanJam");
    }//GEN-LAST:event_bKbliKePilFilmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormAmbacinema().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton A1;
    private javax.swing.JToggleButton A2;
    private javax.swing.JToggleButton A3;
    private javax.swing.JToggleButton B1;
    private javax.swing.JToggleButton B2;
    private javax.swing.JToggleButton B3;
    private javax.swing.JToggleButton C1;
    private javax.swing.JToggleButton C2;
    private javax.swing.JToggleButton C3;
    private javax.swing.JRadioButton ambacong;
    private javax.swing.JRadioButton ambatar;
    private javax.swing.JRadioButton argoNgawi;
    private javax.swing.JButton bKbliKePilFilm;
    private javax.swing.JButton bLnjtKeKonfirmasi;
    private javax.swing.JButton bLnjtKePilKursi;
    private javax.swing.ButtonGroup bgFilm;
    private javax.swing.JComboBox<String> cbJamTayang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelPilFilmDanJam;
    private javax.swing.JPanel jPanelPilKursi;
    private javax.swing.JPanel panelInduk;
    // End of variables declaration//GEN-END:variables
}
